# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "599a8233585663068d4515f7e61b0ef8"
name = "Verify COD Orders"
handle = "verify-cod-orders-1"
application_url = "https://fiscal-scuba-rpm-convicted.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://fiscal-scuba-rpm-convicted.trycloudflare.com/auth/callback",
  "https://fiscal-scuba-rpm-convicted.trycloudflare.com/auth/shopify/callback",
  "https://fiscal-scuba-rpm-convicted.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
