type = "theme_app_extension"
name = "Verify COD Orders Chatbot"

[settings]
chatbot_enabled = true

[[settings.fields]]
key = "chatbot_enabled"
type = "checkbox"
name = "Habilitar Chatbot"
default = true

[[settings.fields]]
key = "chatbot_position"
type = "select"
name = "Posición del Chatbot"
options = [
  { "label" = "Inferior Derecha", "value" = "bottom-right" },
  { "label" = "Inferior Izquierda", "value" = "bottom-left" }
]
default = "bottom-right"

[[settings.fields]]
key = "chatbot_theme"
type = "select"
name = "Tema del Chatbot"
options = [
  { "label" = "Claro", "value" = "light" },
  { "label" = "Oscuro", "value" = "dark" }
]
default = "light"

[[blocks]]
type = "chatbot"
name = "Chatbot"
target = "body" 